version: "3"

services:
  test_data:
    image: alpine
    volumes:
      - ./data_backup.tar.gz:/tmp/data.tar.gz
      - ./test_data/:/data
    command: sh -c "cd /data && rm -rf * && tar -xzf /tmp/data.tar.gz -C /data"

  postgres:
    container_name: agenda
    image: postgres:latest
    depends_on:
      - test_data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agendadb
    ports:
    - 5432:5432
    volumes:
      - ./test_data/data_agendadb-test:/var/lib/postgresql/data
